// <auto-generated />
using System;
using BBS_POS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BBS_POS.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251120125323_Salez")]
    partial class Salez
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BBS_POS.Models.Product", b =>
                {
                    b.Property<int>("p_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("p_id"));

                    b.Property<int>("p_box_size")
                        .HasColumnType("int");

                    b.Property<decimal>("p_buy_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("p_created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("p_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("p_piece_size")
                        .HasColumnType("int");

                    b.Property<decimal>("p_sale_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("p_updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("p_id");

                    b.ToTable("tbl_product");
                });

            modelBuilder.Entity("BBS_POS.Models.Quantity", b =>
                {
                    b.Property<int>("q_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("q_id"));

                    b.Property<int>("box_quantity")
                        .HasColumnType("int");

                    b.Property<int>("p_id")
                        .HasColumnType("int");

                    b.HasKey("q_id");

                    b.HasIndex("p_id");

                    b.ToTable("Quantity");
                });

            modelBuilder.Entity("BBS_POS.Models.Sale", b =>
                {
                    b.Property<int>("s_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("s_id"));

                    b.Property<int>("p_id")
                        .HasColumnType("int");

                    b.Property<string>("p_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("qty_box")
                        .HasColumnType("int");

                    b.Property<int?>("qty_pieces")
                        .HasColumnType("int");

                    b.Property<DateTime>("s_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("s_id");

                    b.HasIndex("p_id");

                    b.ToTable("tbl_sale");
                });

            modelBuilder.Entity("BBS_POS.Models.User", b =>
                {
                    b.Property<int>("u_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("u_id"));

                    b.Property<string>("u_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("u_pwd")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("u_role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("u_usr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("u_id");

                    b.ToTable("tbl_user");
                });

            modelBuilder.Entity("BBS_POS.Models.Quantity", b =>
                {
                    b.HasOne("BBS_POS.Models.Product", "Product")
                        .WithMany("Quantities")
                        .HasForeignKey("p_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BBS_POS.Models.Sale", b =>
                {
                    b.HasOne("BBS_POS.Models.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("p_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BBS_POS.Models.Product", b =>
                {
                    b.Navigation("Quantities");

                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
